--- # conditional playbook
- name: playbook conditional
  hosts: all
  become: true


  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: start httpd service
      service:
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"
